
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpgmtartrnabekgqdire.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwZ210YXJ0cm5hYmVrZ3FkaXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzODIzOTksImV4cCI6MjA1ODk1ODM5OX0.Qd_ag4x_mEwz7cjVOlBESR73MeAnptH7G16_Vv8YTys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: localStorage
  }
});

// Helper function to check if current user is admin
export const isUserAdmin = async (): Promise<boolean> => {
  try {
    const { data: isAdmin, error } = await supabase.rpc('is_admin');
    
    if (error) {
      console.error('Error checking admin status:', error);
      return false;
    }
    
    return isAdmin || false;
  } catch (error) {
    console.error('Exception checking admin status:', error);
    return false;
  }
};

