
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axgzuhuqeogpmidpcdol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4Z3p1aHVxZW9ncG1pZHBjZG9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjUxNjgsImV4cCI6MjA1ODg0MTE2OH0.NF_Ow-LkBInI_82e_NJjCQo_Ap_OEZjwAuQYYG4apiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
