
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpgmtartrnabekgqdire.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwZ210YXJ0cm5hYmVrZ3FkaXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzODIzOTksImV4cCI6MjA1ODk1ODM5OX0.Qd_ag4x_mEwz7cjVOlBESR73MeAnptH7G16_Vv8YTys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
